version: '3'

services:
  postgres:
    image: postgres:11.8-alpine
    ports:
        - '5433:5432'
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_DB: 'studying_nest'
